spring:
  application:
    name: domoShoppingApp

  cloud:
    consult:
      config:
        fail-fast: true
      host: localhost
      port: 8500

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shoppingGroup
      auto-offset-reset: earliest # optional, ensures reading from the earliest offset if no committed offset exists
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: 'user'
    password: '@password'
    hikari:
      schema: shopping
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data
    validate-on-migrate: true
    default-schema: shopping

kafka-config:
    topic: "shopping-group"


